### ISSUE TITLE
bug: maven plugin validation issues

### ISSUE THREAD

**Issue by Jonathan-Zollinger** [Jonathan-Zollinger/jeofetch#2]
calling `mvn clean install` produces this warning message 

```sh
[WARNING] 
[WARNING] Plugin validation issues were detected in 4 plugin(s)
[WARNING] 
[WARNING]  * org.codehaus.mojo:appassembler-maven-plugin:1.10
[WARNING]  * org.apache.maven.plugins:maven-compiler-plugin:3.10.1
[WARNING]  * org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7
[WARNING]  * org.apache.maven.plugins:maven-resources-plugin:3.3.0
[WARNING] 
[WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]
[WARNING] 
```

**Comment by lab596** [comment]
After completing the following steps to install maven: https://phoenixnap.com/kb/install-maven-windows

I ran the command 'mvn clean install' and I was simply met with the warning to replace ${artifactId} with ${project.artifactId}. Upon completion the warning goes away.

**Comment by Jonathan-Zollinger** [comment]
Hi @lab596  thanks for looking in to this, you're right in that the message you're seeing is a warning which needs fixing, but isn't the warning relative to these plugins. for now I think what I'll do is just remove these plugins and add a feature request to compile this to an all inclusive (fat) jar. for now it will work as is. I'll also need to add a request to write a README with instructions on installing this without a fat jar.

Thanks again for all your help! I hope you continue contributing on here!
