### ISSUE TITLE
 Could not find or load main class Main

### ISSUE THREAD

**Issue by lab596** [Jonathan-Zollinger/jeofetch#3]
After cloning the project and attempting to run Main.java in VSCode I am faced with the following error message: 

"The file Main.java isn't on the classpath, the runtime may throw class not found error. Do you want to add the parent folder "jeofetch/src/com/github/jonathanzollinger/jeofetch" to Java source path?". 

This then further prompts me to modify pom.xml to make an adjustment however I am unsure what to change to prevent the following error: 

Error: Could not find or load main class Main
Caused by: java.lang.ClassNotFoundException: Main

**Comment by lab596** [comment]
Upon further inspection, I opened the src file within the repo instead of the whole jeofetch project in VSCode, enabling me to run the Main.java file. However this caused me to find the following error in my terminal: 

Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
        SystemUtils cannot be resolved
        SystemUtils cannot be resolved to a variable

**Comment by Jonathan-Zollinger** [comment]
Thanks @lab596  - I forgot to push my commits from yesterday. I've added them now - commit dc3aa6f61307ecdacc4a518d927447b75197824f addresses this issue. I'll add an automated build to avoid this issue in the future
